### ISSUE TITLE
UnresolvablePlaceholdersException thrown inappropriately

### ISSUE THREAD

**Issue by stephenjfox** [ufoscout/properlty#16]
Properlty's [`getBoolean(String, Boolean)`](https://github.com/ufoscout/properlty/blob/3d7c320535cbf7959147580167db90083f5d3c70/properlty-kotlin/src/main/java/com/ufoscout/properlty/Properlty.kt#L89) behaves unexpectedly and, I would argue, __undesirably__.

### The behavior

Rather than returning null as implied by this block...

```kotlin
fun getBoolean(key: String): Boolean? {
    val value = get(key)
    return if (value == null)
        value
  // elided
}

```

An exception is thrown, which confused me. So I investigated.

### Investigation

The stack trace points to this block of code in [`ReplacerDecoratorReader.java`](https://github.com/ufoscout/properlty/blob/abe842b724c494922c962118e3a0ad0fb492ee36/properlty-common/src/main/java/com/ufoscout/properlty/reader/decorator/ReplacerDecoratorReader.java#L95):

```java
if (!valuesToBeReplacedMap.isEmpty() && !ignoreUnresolvablePlaceholders) {
	final StringBuilder message = new StringBuilder("Unresolvable placeholders: \n");
	valuesToBeReplacedMap.forEach((key, value) -> {
		message.append("key: [");
		message.append(key);
		message.append("] value: [");
		message.append(value.getValue());
		message.append("]\n");
	});
	throw new UnresolvablePlaceholdersException(message.toString());
}

```

Just looking at the Kotlin code, I would expect to get back a null for an "unresolvablePlaceholder" (after setting the `ignoreUnresolvablePlaceholders`, of course).

## Conclusion

I have a `application.properties` file that I am loading, but I don't want to declare the default in that file. 
At my company, changing configuration files and change source files has the same turn around time. Also, we have environment variable loaded in certain environments and I wanted to leave those out for local development.
As a result, I would prefer the particular property that I am __choosing to leave "unresolved"__ return null and defer to the code-level default.

For visuals:

```kotlin
object Configuration {
    val properlty: Properlty.builder()
                              .add("classpath:application.properties")
                              .build()

    val myBoolean = properlty.getBoolean("my.boolean", defaultValue = true) // this throws the exception
}

```

I can submit a PR, but I wanted to discuss first. Given the lack of documentation, I wonder if there's a design guideline I'm simply misunderstanding.

**Comment by ufoscout** [comment]
Hi @stephenjfox 

Could you please provide the full error stacktrace? 
Is the "my.boolean" placeholder is used in the application.properties file? If this is the case then the exception is expected and it has to be solved using a default value:
application.properties file:
```properties
## use my.boolean in the properties file and set its value to 'false' by default
my.value.something=${my.boolean:false}
```

**Comment by stephenjfox** [comment]
@ufoscout I think I was just making the case for the following:

- If a placeholder is in the file, but no default is supplied, __but__ the default is passed into the `getTypeOrDefault()`, the function should return the default supplied.

But if that's unwanted functionality, I'll close the issue

**Comment by ufoscout** [comment]
@stephenjfox 
I still don't understand your use case. This is how it works:

1. if a placeholder is in a file, without a default value, and it cannot be resolved, then an exception is thrown;
2. if a placeholder is in a file, with a default value and it cannot be resolved, then the default is used;
3. if a placeholder is in a file, with or without a default value and it can be resolved, then the resolved is used;
4. when you use `getTypeOrDefault()`, if the key is defined and resolvable, then the associated value is returned, otherwise the default one.

Only in case '1' an exception is thrown, and this is the desired behaviour.
Please be sure not to confuse keys and placeholders; all of the `getType...()` variants work on keys (not placeholders) and return their values. E.g., config.properties:
```properties
key.one=${key.two}-${placeholder.one:default}
key.two=value
```

In this example, you have two keys ('key.one' and 'key.two') instead of three ('placeholder.one' is not a key).
